server:
  port: 8081
#logging:
#  level:
#    org.springframework: debug

jwt:
  header: Authorization
  tokenHead: "Bearer "
  secret: mySecret
  expiration: 86400 # 单位秒=24小时
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
