spring:
  datasource:
    url: jdbc:mysql://172.17.100.27:3306/security?useUnicode=yes&characterEncoding=utf-8&useSSL=false
    username: root
    password: JR2018,.
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 148.70.63.176
    port: 36079
    password: 1234qwer
